### ISSUE TITLE
Layer map view does not zoom to layer correctly

### ISSUE THREAD

**Issue by timlinux** [kartoza/geonode#289] opened 2017-07-01 08:27 UTC
A newly uploaded layer shows in the layer list fine but it does not zoom correctly to the layer:

http://geonode.kartoza.com/layers/geonode:tandale_imagery

<img width="1209" alt="screen shot 2017-07-01 at 10 26 53 am" src="https://user-images.githubusercontent.com/178003/27760450-d65ccf28-5e47-11e7-8337-91e10a7216c7.png">

child of #457

**Comment by lucernae** [comment] 2017-07-03 11:47
Same problem with #287 :

Caused by:

- layer uploaded using non-default CRS, EPSG:32737. But we should expect this to work
- CRS info not saved by geonode. It will always default to 4326. We can fix this in qgis_server signal layer post_save
- Leaflet itself can't handle this CRS correctly. We should tell leaflet to use 4326.
- To accomodate above, we should make sure all tile request uses 4326.
- All calculation that needs bounding box (such as Layer > Set thumbnail) should use 4326.

**Comment by lucernae** [comment] 2017-07-03 18:00
@timlinux @gubuntu Can I ask some perhaps "stupid" questions? I'm getting really confused.
So, I was trying to convert all bbox passed to leaflet in the format EPSG:4326. 

In summary, what I did was:
- I added a hook in qgis_server backend to put your layer CRS correctly (32737)
- I converted every bbox passed to leaflet to use CRS EPSG:4326
- I converted every bbox passed to thumbnail generation to use EPSG:4326. Mainly because our QGIS Server request url is using this CRS
- When I view layer, I got thrown off some degree north, but thumbnail is showing. If I scroll down, the map is rendered (I think) in the correct location.
- I hover to the correct location and click set thumbnail (will generate thumbnail from map extent). But now, the thumbnail only shows transparent image, it seems in the wrong location.
- Confused, I tried to change leaflet CRS to EPSG:3857. Now view layer zooms to correct extent. But what I passed to leaflet is extent in EPSG:4326, and every tile and wms code I saw in the template uses EPSG:4326 to build request. However, if I set leaflet CRS to EPSG:4326, the extent got thrown off.

# Question:

Can I safely assumes that this is a bug in leaflet? CMIIW, wasn't 4326 and 3857 is the same? Or did I miss something? Is it safe for me to throw all bbox and coordinate as 4326, but set leaflet CRS to 3857? because it seems this combination works, but people who read the code will be getting confused.

**Comment by gubuntu** [comment] 2017-07-03 18:38
- a user should be able to upload a layer in any properly defined CRS. QGIS will read it an transform it on the fly like any other layer
- in a WMS request, the CRS and BBOX must match. In our case as with most web maps the CRS must be 3857 and the BBOX must be in 3857 coordinates. And the response will be in 3857

If it's not working like this I doubt the issue is with Leaflet

**Comment by lucernae** [comment] 2017-07-04 08:57
There's no issue with QGIS, we are using EPSG:4326 in the request and bbox.

**Comment by NyakudyaA** [comment] 2017-07-04 12:22
Layers loaded with `CRS:54009` 
Thumbnail: working
Tiles: Misaligned

Full extent
![crs2](https://user-images.githubusercontent.com/2510900/27829855-f4423e64-60c3-11e7-859e-47e44c5e9341.png)

Layer extent
![crs](https://user-images.githubusercontent.com/2510900/27829865-04dd658c-60c4-11e7-9e4a-d069401c0c10.png)

**Comment by boney-bun** [comment] 2017-07-04 15:13
@lucernae i guess we'd have to specify the CRS in the leaflet from now on.
the leaflet has [CRS class](http://leafletjs.com/reference-1.1.0.html#crs), but never being used in the code. the class provides methods converting point to LatLng, vice versa. it has projection function as well. 
cmiiw perhaps it can fix the layout problem on the UI.

**Comment by lucernae** [comment] 2017-07-05 00:44
Oops, must be autoclose from github, I will reopen it for testing in production.
Please close when it is considered solved.

Anyway, for some explanation:
Yes @boney-bun , as what I was describing up above, I set leaflet CRS to EPSG:4326 previously.

Reason:
- Leaflet doesn't support on the fly reprojection, so we have to use the same CRS for all layers. So I set it to EPSG:4326
- Leaflet have limited support for available CRS. Currently only EPSG:4326 and EPSG:3857 commonly used. We can't have, for instance, EPSG:32737 like what @timlinux used in the layer. So, I set it to EPSG:4326

Result:
- It somehow behaves wrong (which is why made me assumes this is a bug in leaflet). All the layers were operating in EPSG:4326, bbox too. But leaflet displayed it incorrectly, it is a little bit off to the south. But thumbnail is working, and tile generated at the correct position, so I concluded this is not the issue in QGIS.

Because of this result, out of curiosity, I changed leaflet CRS to EPSG:3857. Then it works, but this is wrong IMO, because layers and bbox is using EPSG:4326.

So, what I did in the PR is for leaflet to use this EPSG:3857.
I tried reuploading @timlinux 's layers and it worked.

CC @NyakudyaA could you test your layer again? And close this if it is fixed?

**Comment by boney-bun** [comment] 2017-07-05 06:02
thanks for your thorough explanations @lucernae 
i get your point now.
looking at this [leaflet ticket](https://github.com/Leaflet/Leaflet/issues/2553), i think your opinion is valid. 
leaflet indeed doesn't support different CRS on the same map.  
well, at least for now.
also, please note that we use leaflet 0.7.7.

**Comment by NyakudyaA** [comment] 2017-07-05 07:18
@lucernae I tried uploading the same layer with `EPSG:54009` and it did not work. Still having the issue
I have left the layer in staging so that you can use it to debug. http://staging.geonode.kartoza.com/layers/geonode:tanzania_epsg_54009

**Comment by lucernae** [comment] 2017-07-05 07:20
Did you try it only in staging? Because I haven't updated staging lately. All goes straight to production.
Did you put the layer on `geosafe_data`, so I don't have to upload it.

**Comment by NyakudyaA** [comment] 2017-07-05 07:22
I tried it on both staging and production.  Yes I have put it in the bit sync folder

**Comment by lucernae** [comment] 2017-07-05 07:39
I tried it on my local, it seems QGIS can't detect the projection itself (which probably means GDAL can't detect it).
How do you set this projection @NyakudyaA ?

<img width="1050" alt="screen shot 2017-07-05 at 14 37 38" src="https://user-images.githubusercontent.com/831865/27854114-ad51ca34-618f-11e7-8f8f-54fc95879e25.png">

**Comment by NyakudyaA** [comment] 2017-07-05 07:52
@lucernae  can you just search the projection `EPSG:54009` in QGIS. The main reason I was using that projection is that the specifications of the data said so. 

I think the main problem is that if you search for that projection it shows up in QGIS but once you load the layer in QGIS. QGIS reads the CRS as a user defined CRS.
![user](https://user-images.githubusercontent.com/2510900/27854510-5a152168-6167-11e7-8692-8e3dc04b2cae.png)

![userd](https://user-images.githubusercontent.com/2510900/27854516-64b5785c-6167-11e7-9b24-45cbd8cbfcc8.png)

![gdal](https://user-images.githubusercontent.com/2510900/27854535-6ebf1484-6167-11e7-860a-af6dcc4f1022.png)

Maybe we need not worry about such edge cases?

**Comment by lucernae** [comment] 2017-07-05 11:34
I mean, can you teach me how to set the projection, so I can replicate it and know where to look the EPSG code?

The current method I use in geonode is use GDAL to read projection info and search for EPSG code. But I can't found it for this case, as you can see in PROJCS description, there is no EPSG code.
Do you have any suggestion on where  can get the EPSG code?
Or should I take the Projection value (Mollweide) and convert it to EPSG code somehow?

**Comment by NyakudyaA** [comment] 2017-07-05 11:51
Ok @lucernae. You can look at https://epsg.io/54009 >  I think native gdal is playing tricks with this projection. I tried to translate on my laptop and it just fails. I think we can close this ticket because this might be an edge case and we do not really want to spend time on 1 issue where the majority might not even encounter. 

![out](https://user-images.githubusercontent.com/2510900/27863128-f8f96494-6188-11e7-85ab-26ac71d40a0c.gif)

**Comment by gubuntu** [comment] 2017-07-06 08:26
Guys please see https://github.com/kartoza/geonode/issues/289#issuecomment-312711280 again.

- any uploaded layer should just work on the QGIS side as long as it has CRS metadata that QGIS can pick up. The user should get feedback to provide it if this doesn't exist. So @lucernae can you explain why you even need to use GDAL to find the CRS?

- once the layer is available in QGIS, all requests must use EPSG:3857 (no 4326) since OSM and other public web map services are 3857.

It shouldn't be any more complicated than that. 

If you don't understand this maybe we need a voice call.

**Comment by lucernae** [comment] 2017-07-06 10:59
> - any uploaded layer should just work on the QGIS side as long as it has CRS metadata that QGIS can pick up. The user should get feedback to provide it if this doesn't exist. So @lucernae can you explain why you even need to use GDAL to find the CRS?

Geonode saves the bbox in the database, but it didn't save the CRS. So when we operate with bbox, such as giving the extent for thumbnail, the CRS is wrong, it didn't match with the bbox that it reads. So, I had to get this CRS using GDAL/OGR to save this information to database for that kind of operation. Meanwhile, in this case QGIS is working normally as long as this CRS is set in the TIF layer. So my fix is working as long as there is EPSG code in the TIF layer.
But the next problem @NyakudyaA and I discussed, is with this particular layer, GDAL can't find the EPSG code set in the layer. Then QGIS also didn't catch the projection, so both geonode and QGIS didn't use the correct CRS. We were discussing that maybe this is just an edge cases where GDAL didn't put EPSG code only for this Mollweide projection.

> - once the layer is available in QGIS, all requests must use EPSG:3857 (no 4326) since OSM and other public web map services are 3857.
It shouldn't be any more complicated than that. 
If you don't understand this maybe we need a voice call. 

What makes it confusing is leaflet didn't work as expected. When I set both leaflet and QGIS to use EPSG:4326, the coordinates is off. When I set both leaflet and QGIS to use EPSG:3857, the coordinates is off too. What works is when I set leaflet coordinates to use EPSG:3857, but sent the WMS and tiles request from leaflet as if it is coming from EPSG:4326, then recalculate the coordinate to convert it to EPSG:3857, then made QGIS request using CRS EPSG:3857.

**Comment by gubuntu** [comment] 2017-07-08 10:11
- perhaps all boxes should be saved in EPSG:3857 so there's no confusion. 
- then set up the map (layers, map and analysis pages) so:
```var map = L.map('map', {
    crs: L.CRS.EPSG3857
});```

and all requests will be made in 3857 and map tiles will be returned in 3857.. No GDAL or other logic required. And no matter what the native CRS is of the layer (as long as QGIS has detected it properly.)

IF QGIS can't pick up the CRS properly on upload (how do we tell?) , the user should get a message to upload again with a proper header or prj file.

**Comment by boney-bun** [comment] 2018-06-21 05:51
i'm trying to understand the issue. 
Basically we have to do otf projection for the coordinate system other than 3857.
If the geonode doesn't understand the given CRS/SRS, we should reject and warn the user to upload a proper file. 
However, in the case of `EPSG:54009`, we know that this CRS is valid. 
So, the geonode is expected to recognize it.

for this case, here are what I found:

> Geonode saves the bbox in the database, but it didn't save the CRS. 

@lucernae I think geonode 2.8 stores SRID along with bboxes as denoted on this line of code: https://github.com/kartoza/geonode/blob/2.8.x-qgis_server/geonode/base/models.py#L698
cmiiw, the SRID is basically information about SRS/CRS. So geonode has information about CRS/SRS from *srid* field.
Also, to comment on @gubuntu :

>once the layer is available in QGIS, all requests must use EPSG:3857 (no 4326) since OSM and other public web map services are 3857.

@lucernae to confirm: the default geonode's reference system most likely is 4326 (as defined on the *srid* variable in *ResourceBase* class). 

@NyakudyaA It seems that `EPSG:54009` is unrecognized within geonode.
How do we teach the geonode to understand the *54009*?
Running the below sql script will return nothing:
```
SELECT * FROM spatial_ref_sys WHERE srid = 54009
```
So, I manually added the coordinate system to geonode via postgis (`spatial_ref_sys` table) as described in @NyakudyaA  link (https://epsg.io/54009). Then, i reuploaded the layer again.
Unfortunately, geonode still doesn't recognize the coordinate system (geonode will fill the srid field with `EPSG:None`).
**Note: epsg.io defines the srid as `ESRI:54009`, not `EPSG:54009`.**

I think if we can make the geonode recognize the 54009, the problem may be gone.

**Comment by gubuntu** [comment] 2018-06-25 15:34
> Basically we have to do otf projection for the coordinate system other than 3857
no, QGIS should handle that automatically

> If the geonode doesn't understand the given CRS/SRS, we should reject and warn the user to upload a proper file
You mean if QGIS does not recognise the CRS? Well, GeoNode and QGIS both have to have the same understanding of the CRS on upload. If it is missing or unrecognisable then there should be user feedback. Surely this all works with Geoserver backend and we should be emulating that with QGIS?

CRS is a synonym of SRID (CRS == SRID)

Not all standard SRIDs are described by the EPSG. Some have other authorities (e.g. ESRI) and some are user defined. 

If they are user defined then full SRID strings (in WKT or proj4 format) need to be passed instead of an EPSG code. 

PostGIS maintains its own database of SRID codes in spatial_ref_sys.

GeoNode (I think) uses GDAL's own database of SRID codes. (So adding a defition to PostGIS won't make any difference since GeoNode is not aware of spatial_ref_sys. But it will result in an error if new layer is loaded into PostGIS with an SRID that is not in spatial_ref_sys) 

Geoserver maintain its own separate database of SRIDs as well. 

The CRS and projection specified on upload, as long as it is there and is valid, should be handled smoothly and in the same way by GeoNode, no matter what back-end it has.

**Comment by NyakudyaA** [comment] 2018-09-05 20:08
@boney-bun I have tested with various layers in UTM and they all render fine with thumbnails being created

**Closed** 2018-09-11 08:30 UTC
Labels: bug, testing
