### ISSUE TITLE
metadata wizard doesn't load

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#521] opened 2018-11-03 14:19 UTC

**Comment by NyakudyaA** [comment] 2018-11-05 10:18
@gubuntu cc @boney-bun  I think this is caused by the metadata regions which I deleted. Geonode does not handle metadata regions properly and this causes it to not load everything.

Here is a sample layer that I have loaded for Mozambique in testing.
If you look at the default metadata regions assigned to it.
![metadata-regions](https://user-images.githubusercontent.com/2510900/47990839-3ffbb200-e0f1-11e8-8028-37f1eccbc147.png)

Just because I deleted some of the regions now Geonode still looks for them and fails to find them and this affects the metadata region.

I suggest the following.

* We can restore all the data with all the default metadata regions and then add those other ones for Mozambique with relation to #466 
## Fix the way metadata regions are allocated to layers in Geonode.
* The scheme for this should be like >> `Global` - `Continent` - `Region` - `Country` - `Provinces` (If a user has added them) - `District` until we get the smallest unit defined by a user.
*  If a layer is uploaded then it should get it's regions from the smallest unit defined (Which is Country by default). 
* If for instance we identify that the data belongs to Mozambique then the metadata regions should automatically be `Global` - `Continent` - `Region` - `Country` and a user can add other smaller units if he has defined them
* Investigate how Geonode is currently assigning  because this is not correct. 
* If a user has deleted some of the regions how should geonode act to prevent you from uploading data that lies outside the regions defined.
NB: In PostgreSQL we could use a function ST_Within to check if the geometry lies within another. But in this case we need something more clever and fast since it will have to check against all country regions to see if it lies within and that the regions table does not have geometry. 
In javascript how do we do this and improve the current Geonode implementation

**Comment by gubuntu** [comment] 2018-11-06 19:33
@NyakudyaA if you can't get it to work with modified regions then revert it to a working condition and put your suggestions in upstream tickets. 

e.g. I searched for 'manica' under regions and got 0 results yet there are several layers that are in or intersect with manica

**Comment by NyakudyaA** [comment] 2018-11-06 19:37
I did not assign the metadata keywords to the districts and sub-districts because it would have taken me a long time to do that and look at which layer intersects which. In fact, the majority of the layers are of national coverage. If a user smaller datasets then they can allocate the regions to the smallest unit

**Comment by gubuntu** [comment] 2018-11-06 20:04
OK...but the metadata wizard is still not loading as per OP - can you fix that?

**Comment by NyakudyaA** [comment] 2018-11-16 06:15
I have fixed this for now. I have opened a ticket upstream. This issue turns out was caused by the characters used in the Portuguese language. I had to change the encoding to `PGCLIENTENCODING=UTF8` 

![screenshot 2018-11-16 at 08 14 19](https://user-images.githubusercontent.com/2510900/48601209-a8f7eb00-e977-11e8-8304-18708138a4de.png)

I have created an issue upstream with how metadata regions should be handled

**Closed by NyakudyaA** 2018-11-16 06:15 UTC
Labels: bug, ready
