### ISSUE TITLE
Clip and Ship

### ISSUE THREAD

**Issue by cchristelis** [kartoza/geonode#263] opened 2017-06-12 08:06 UTC
# Problem

We would like to allow users to select an AOI and get a clipped dataset back.

# Proposed solution

Send an​ AOI to the QGIS/GeoServer backend and return a link that the user can download this clipped data.

**Comment by meomancer** [comment] 2017-06-13 05:21
hi @cchristelis 
is there any dataset that we could use?

**Comment by dimasciput** [comment] 2017-06-14 05:53
What is the user flow for this in the front end?

**Comment by gubuntu** [comment] 2017-06-14 08:41
duplicate of #150

**Closed** 2017-06-14 08:41 UTC
Labels: enhancement, HaitiData
